#!/bin/bash -eux

# go to the top of the hierarchy
cd $(git rev-parse --show-toplevel)

find . -type f |
fgrep -v .git  |                            # get all the real files
while read i; do
  date="$( git log -1 --format=%ci -- $i)"  # a format touch understands
  [ "$date" ] && touch --date="$date" $i
done
